apiVersion: v1
kind: Service
metadata:
  name: short-url-svc
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8000
  selector:
    app: short-url
