apiVersion: v1
kind: Service
metadata:
  name: mongo-svc
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
    - name: mongo
      port: 27017
      protocol: TCP
      targetPort: 27017
  selector:
    app: mongo-deployment
